### ISSUE TITLE
[Bug] 1.2.1 Update - Download Button is Gone

### ISSUE THREAD

**Issue by shaneholloman** [tehrobber/civitai-one-click-dl#5]
Version before this was working. After I noticed this, I reinstalled and still a no go 
I'm using Chrome Version 109.0.5414.121 (Official Build) (64-bit) with Tamper Monkey 4.18.1. I used a time delay on screen shot so you can see the script executed withut rendering dwnload button. 

> Refreshing does not help like it usually did in previous version. Hope this helps

![image](https://user-images.githubusercontent.com/1563909/218642006-42131065-6ee4-4798-8762-188a0638ce2f.png)

**Comment by tehrobber** [comment]
Do you have steps to reproduce this?

- Did you navigate directly to this URL?
- Did you navigate to this model from the homepage/search?

**Comment by tehrobber** [comment]
Try again with 1.3.1 and let me know the above info if you still see issues.

**Comment by tehrobber** [comment]
I just reproduced this while using this script myself. It happened when opening a new tab/window.

Fixed with 1.3.2 - https://github.com/tehrobber/civitai-one-click-dl/commit/bef771a019ce7236184ac963f6d68ce59ce743fe
Hopefully the last time this happens, it's tricky to get the button to insert only once.

**Comment by shaneholloman** [comment]
That sorted it mate! noice!
